# Uncomment the lines below you want to change by removing the # in the beginning

# A list of devices you want to take the screenshots from
devices(
  [
    "iPhone 8"
  ]
)

languages(
  [
    "en-US"
  ]
)
scheme("natureFMUITests")

output_directory("./screenshots")

clear_previous_screenshots(true)

override_status_bar(true)

# Arguments to pass to the app on launch. See https://docs.fastlane.tools/actions/snapshot/#launch-arguments
# launch_arguments(["-favColor red"])

